---
apiVersion: v1
kind: Pod
metadata:
  name: 2in1
spec:
  containers:
    - image: nginx:1.23
      name: nginx
      ports: 
        - containerPort: 80
    - image: jenkins/jenkins:jdk11
      name: jenkins
      ports:
        - containerPort: 8080
          