--- 
apiVersion: v1
kind: Pod
metadata:
  - name: ex2
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerport:80
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d
